# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  - push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up
        run: make setup

      - name: Run tests
        run: make test
          
      - name: Run lint
        run: make lint
